// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// 🔍 Debug: طباعة المتغيرات في الكونسول للتأكد من وصولها
// ده هيظهر في الـ Console في المتصفح عشان نتأكد إن الـ Env Variables شغالة
if (typeof window !== 'undefined') {
  console.log('🔐 Supabase Check:', {
    url: SUPABASE_URL?.trim(),
    key: SUPABASE_PUBLISHABLE_KEY ? '✅ Present' : '❌ Missing',
    projectId: import.meta.env.VITE_SUPABASE_PROJECT_ID
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});